[assembly: System.Reflection.AssemblyTitleAttribute("Web.Common Library")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Web.Common Library")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright (c) 2016 Lukasz Jaskiewicz. All Rights Reserved.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.0.0.0")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.0.0")]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETStandard,Version=v1.6")]
